
$projectData = @(
    @{id=1; slug="hallucination"; title="Hallucination"; category="pc-game"; tools="Unity"; video="https://youtu.be/sfLfRJljKg8"; folder="Hallucination"; desc="3D PC-based first-person horror game developed using Unity to study player tension and engagement."; full="This is a 3D PC-based first-person horror game developed for my Final Year Project using Unity to study player tension and engagement. I implemented three enemy behavior systems using Unity’s AI navigation system: constant-chasing, jump-scare, and scene-triggered chasing."},
    @{id=2; slug="the-last-witch-soul"; title="The Last Witch Soul"; category="pc-game"; tools="Unreal Engine"; video=""; folder="The Last Witch Soul"; desc="Creative puzzle ball game developed using Unreal Engine with narrative elements."; full="This is a creative puzzle ball game developed using Unreal Engine with narrative elements. I implemented core gameplay systems, including ball movement, interaction, item collection and simple puzzle mechanics."},
    @{id=3; slug="the-last-light-of- divinity"; title="The Last Light of Divinity"; category="pc-game"; tools="Unreal Engine"; video=""; folder="The Last Light of Divinity"; desc="3D PC-based third-person action-adventure game developed using Unreal Engine."; full="This is a 3D PC-based third-person action-adventure game developed using Unreal Engine. I implemented environment design and waypoint-based navigation using Unreal Blueprints."},
    @{id=4; slug="backrooms-hunt-for-escape"; title="Backrooms: Hunt for Escape"; category="pc-game"; tools="Unity"; video="https://youtu.be/ONDL92dZvpk"; folder="Backrooms Hunt for Escape"; desc="3D PC-based multiplayer PvP FPS game in a backrooms-themed environment using Unity and Photon."; full="This is a 3D PC-based multiplayer PvP FPS game in a backrooms-themed environment using Unity and Photon. I implemented core gameplay mechanics, including shooting, ammo refilling, point collection and health recovery."},
    @{id=5; slug="lost-era-crystal-hunt"; title="Lost Era: Crystal Hunt"; category="pc-game"; tools="Unity"; video="https://youtu.be/EsIabz_O_Vo"; folder="Lost Era Crystal Hunt"; desc="3D PC-based multiplayer PvE adventure game set in a historical-themed environment."; full="This game trailer shows a 3D PC-based multiplayer PvE adventure game set in a historical-themed environment. I implemented core gameplay systems, including shooting, special skills, spot hiding, item collection and interaction and enemy chasing using Unity’s AI navigation (NavMesh)."},
    @{id=6; slug="hollow-nightmare"; title="Hollow Nightmare"; category="pc-game"; tools="Unity"; video=""; folder="Hollow Nightmare"; desc="3D endless runner game set in a Halloween-themed environment."; full="I developed a 3D endless runner game set in a Halloween-themed environment. I implemented core gameplay mechanics, including running and jumping movement, lane-swiping controls, obstacle avoidance, coin collection, point-tracking system and endless track spawning system."},
    @{id=7; slug="merlins-curse"; title="Merlin’s Curse"; category="pc-game"; tools="Unity"; video=""; folder="Merlin’s Curse"; desc="3D PC-based open-world third-person adventure game with five levels developed using Unity."; full="This is a 3D PC-based open-world third-person adventure game with five levels developed using Unity. I implemented core puzzle gameplay systems, including interaction, item collection, puzzle-trigger mechanics and multiple puzzle managers for different puzzle types (sequence-based, maze-based, and jigsaw puzzles)."},
    @{id=8; slug="the-eyeball-adventure"; title="The EyeBall Adventure"; category="pc-game"; tools="Unity"; video=""; folder="The EyeBall Adventure"; desc="3D narrative-driven ball game with an eyeball protagonist across two levels using Unity."; full="I developed a 3D narrative-driven ball game with an eyeball protagonist across two levels using Unity for the first time. I implemented core gameplay systems, including ball movement, item collection and OnTriggerEnter-based interactions."},
    @{id=9; slug="viral-havoc"; title="Viral Havoc"; category="pc-game"; tools="Unity"; video=""; folder="Viral Havoc"; desc="3D PC-based FPS game developed using Unity with three levels."; full="This is a 3D PC-based FPS game developed using Unity with three levels. I Implemented core gameplay systems, including shooting mechanics, ammo refilling, enemy attack behavior, health and damage systems and environment design."},
    @{id=10; slug="greeting-card"; title="Greeting Card"; category="ar-application"; tools="Unity"; video="https://youtu.be/3fu1yMaTd_4"; folder="Greeting Card"; desc="Simple AR greeting card created using Unity’s built-in Vuforia Engine to celebrate Halloween."; full="This is a simple AR greeting card created using Unity’s built-in Vuforia Engine to celebrate the Halloween festival. It features engaging interactions, animations and mini-games designed to provide a fun and enjoyable experience for the receiver."},
    @{id=11; slug="business-card"; title="Business Card"; category="ar-application"; tools="Unity"; video="https://youtu.be/JG-xxunFk9w"; folder="Business Card"; desc="Simple AR business card created using Unity’s built-in Vuforia Engine to introduce myself."; full="This is a simple AR business card created using Unity’s built-in Vuforia Engine to introduce myself through fun and engaging interactions and animations. It presents my basic personal information, portfolio and hobby, allowing others to learn more about me in an interactive and memorable way."},
    @{id=12; slug="the-three-little-pigs"; title="The Three Little Pigs"; category="ar-application"; tools="Unity"; video="https://youtu.be/kBp8z2v1SRc"; folder="The Three Little Pigs"; desc="AR storybook application based on The Three Little Pigs for children aged 7–12 years old."; full="This is an AR storybook application based on The Three Little Pigs for children aged 7–12 years old developed using Unity’s built-in Vuforia Engine. It implemented simple interaction systems and mini-games to support immersive and engaging storytelling for children."},
    @{id=13; slug="survival-island"; title="Survival Island"; category="vr-game"; tools="Unity"; video=""; folder="Survival Island"; desc="3D VR survival-themed game set on a deserted island developed using Unity."; full="This is a 3D VR survival-themed game set on a deserted island developed using Unity. I implemented core gameplay systems, including interaction and item collection using XR Grab Interactable and XR Socket Interactor scripts."},
    @{id=14; slug="underwater-monument"; title="Underwater Monument"; category="environment-design"; tools="Unity"; video="https://youtu.be/y5KjFyN3VGU"; folder="Underwater Monument"; desc="Underwater monument environment design using Unity terrain and online assets."; full="I created an underwater monument environment design using Unity terrain and online assets. This environment is used as one of the levels in Merlin’s Curse."},
    @{id=15; slug="human-village"; title="Human Village"; category="environment-design"; tools="Unreal Engine"; video="https://youtu.be/WumFpXGj7FM"; folder="Human Village"; desc="Human village and core crystal monuments environment design using Unreal Engine terrain."; full="I created a human village and core crystal monuments environment design using Unreal Engine terrain. This environment is used as one of the levels in the game “The Last Light of Divinity”."},
    @{id=16; slug="study-room-modeling"; title="Study Room"; category="3d-modeling"; tools="Autodesk Maya"; video=""; folder="Study Room"; desc="Modeled a study room using Autodesk Maya, including table, chair and various props."; full="I modeled a study room using Autodesk Maya, including a study table, gaming chair, small desk, book rack, shelves, and other essential props that fit the study room theme."},
    @{id=17; slug="poor-house"; title="Poor House"; category="3d-modeling"; tools="Autodesk Maya"; video=""; folder="Poor House"; desc="Modeled a poor house with a cyberpunk background style using Autodesk Maya."; full="I modeled a poor house with a cyberpunk background style using Autodesk Maya. I also assign texture and materials to the model using Autodesk Maya."},
    @{id=18; slug="stationery-love-story"; title="Stationery Love Story"; category="3d-animation"; tools="Autodesk Maya"; video="https://youtu.be/S6XAFA_4FbU"; folder="Stationery Love Story"; desc="3D animation for stationeries using keyframing and motion path techniques."; full="I created a 3D animation for stationeries in Autodesk Maya using keyframing and motion path techniques."},
    @{id=19; slug="walk-cycle-run-cycle"; title="Walk Cycle & Run Cycle"; category="3d-animation"; tools="Autodesk Maya"; video="https://youtu.be/jCXWr0_RwhU"; folder="Walk Cycle & Run Cycle"; desc="3D animation of walk cycle and run cycle for both human and animal."; full="I created a 3D animation of walk cycle and run cycle for both human and animal using Autodesk Maya by animating the rig of the model."},
    @{id=20; slug="life-of-a-depressed-girl"; title="Life of a Depressed Girl"; category="2d-animation"; tools="Adobe Animate"; video="https://youtu.be/24jxspQBKKI"; folder="Life of a Depressed Girl"; desc="Short 2D animation highlighting mental health issues faced by students."; full="This short 2D animation was created using Adobe Animate. It tells the story of a depressed girl who struggles with academic pressure and portrays her emotional breakdown and suicidal thoughts, aiming to highlight mental health issues faced by students."},
    @{id=21; slug="meowtivation-journey"; title="Meowtivation Journey"; category="2d-animation"; tools="Adobe Animate"; video="https://youtu.be/K8fPYVBd9DE"; folder="Meowtivation Journey"; desc="Short 2D animation depicting a magical journey in a cat kingdom for healing."; full="This short 2D animation continues the story of “Life of a Depressed Girl” created using Adobe Animate. It depicts a magical journey of the girl in a cat kingdom that helps to guide her toward healing and recovery from depression."},
    @{id=22; slug="study-room-105"; title="Study Room #105"; category="video-editing"; tools="CapCut"; video="https://youtu.be/2e-n9d6Lr9c"; folder="Study Room #105"; desc="150-second long-take video with horror-themed narrative elements."; full="I created a 150-second long-take video with horror-themed narrative elements. The video was not further edited in terms of cuts but only blending visual effects and sound effects were adjusted using CapCut to enhance the atmosphere."},
    @{id=23; slug="japan-promo-video"; title="Japan Promo Video"; category="video-editing"; tools="Adobe After Effect"; video="https://youtu.be/2yUmsrNCudc"; folder="Japan Promo Video"; desc="Short travel promotional video about Japan country using After Effects."; full="This video is a short travel promotional video about Japan country edited using Adobe After Effects to implement the techniques of masking, rotoscoping and keyframing and blending effects."},
    @{id=24; slug="batu-nisan-last-carver"; title="Batu Nisan - The Last Carver"; category="video-editing"; tools="CapCut"; video="https://youtu.be/M4cnHPe702M"; folder="Batu Nisan - The Last Carver"; desc="Documentary short film exploring the last Chinese Batu Nisan carver craft."; full="This documentary short film explores a sunset industry by visiting and interviewing the last Chinese Batu Nisan carver, documenting his craft and preserving the story of a fading tradition."},
    @{id=25; slug="happy-birthday"; title="Happy Birthday"; category="video-editing"; tools="CapCut"; video="https://youtu.be/ft9aNLwqPOA"; folder="Happy Birthday"; desc="Short film presenting a horror and suspense narrative centered on teammates."; full="This short film presents a horror and suspense narrative centered on a group of teammates discussing their ideas through an online meeting. The blend of reality and imagined scenes enhances the sense of mystery and tension."},
    @{id=26; slug="visual-soundscape"; title="Visual Soundscape"; category="audio-editing"; tools="Adobe Audition"; video="https://youtu.be/ouA243uio0E"; folder=""; desc="Soundscape inspired by 'Jurassic World' where humans and dinosaurs coexist."; full="Based on the image, I created a soundscape using Adobe Audition that present an imaginative scenario where humans and dinosaurs coexist in the same environment, inspired by the “Jurassic World” film series."},
    @{id=27; slug="radio-sign-call"; title="Radio Sign Call"; category="audio-editing"; tools="Adobe Premium Pro"; video="https://youtu.be/1dzacSJMt9Y"; folder=""; desc="Short radio station opening jingle for a fictional K-pop radio channel."; full="I created a short radio station opening jingle for a fictional K-pop radio channel using Adobe Premium Pro by blending different K-pop music styles to create an energetic and engaging introduction that attracts listeners."},
    @{id=28; slug="radio-play-production"; title="Radio Play Production"; category="audio-editing"; tools="Adobe Audition"; video="https://youtu.be/i7NchGumFxU"; folder=""; desc="Radio play production focusing on McDonald’s drive thru service."; full="I created a radio play production focusing on McDonald’s drive thru service to promote the concept of taking a brief, relaxing moment during a McDonald’s drive-thru experience as a way to escape from the pressures of a daily routine."},
    @{id=29; slug="10-types-of-dmt-student-life"; title="10 Types of DMT Student Life"; category="audio-editing"; tools="Adobe Audition & Adobe Premium Pro"; video="https://youtu.be/-2g4eGlql-U"; folder=""; desc="10-minutes short comedy video reinterpreting scenes from 'No More Bets'."; full="This 10-minutes short firm used the 2023 Chinese film “No More Bets” as the primary inspiration and footage source for our storytelling project to reinterpret the scenes and style to create a short comedy video using our own edited sound effect and human voice-over."},
    @{id=30; slug="boostify"; title="Boostify"; category="software-development"; tools="Visual Studio Code"; video=""; folder="Boostify"; desc="Health & Fitness App combining workout and nutrition tracking."; full="This Health & Fitness App, Boostify is developed and it combines both workout and nutrition tracking functions while also offering a more user-friendly interface to enhance the overall user experience."},
    @{id=31; slug="promotional-flyer"; title="Promotional Flyer"; category="graphic-design"; tools="Adobe InDesign"; video=""; folder=""; desc="Promotional flyer for a fictional Miniso Gryffindor product collection."; full="I created a promotional flyer for a fictional Miniso Gryffindor product collection using Adobe InDesign. The design incorporates a red and gold color palette to reflect Gryffindor’s iconic identity, while maintaining a clean and modern layout to enhance visual impact and brand appeal.", images=@("/assets/Asgm_1 Flyer_page-0001.jpg")},
    @{id=32; slug="lilo-stitch-newsletter"; title="Lilo & Stitch Newsletter"; category="graphic-design"; tools="Adobe InDesign"; video=""; folder="Lilo & Stitch"; desc="Newsletter design inspired by Lilo & Stitch."; full="I created a newsletter design inspired by Lilo & Stitch using Adobe InDesign."},
    @{id=33; slug="horror-rapunzel"; title="Horror Rapunzel Poster"; category="graphic-design"; tools="Adobe Photoshop"; video=""; folder=""; desc="Horror-themed Rapunzel poster design."; full="I created a horror-themed Rapunzel poster design using Adobe Photoshop.", images=@("/assets/Poster_1.jpg")},
    @{id=34; slug="horror-inside-out"; title="Horror Inside Out Poster"; category="graphic-design"; tools="Adobe Photoshop"; video=""; folder=""; desc="Horror-themed Inside Out poster design."; full="I created a horror-themed Inside Out poster design using Adobe Photoshop.", images=@("/assets/Poster_2_page-0001.jpg")}
)

$jsContent = "export const projects = ["

foreach ($p in $projectData) {
    $images = "[]"
    if ($p.folder -ne "") {
        $folderPath = "public/assets/$($p.folder)"
        if (Test-Path $folderPath) {
            $files = Get-ChildItem -Path $folderPath -File | Select-Object -ExpandProperty Name
            $imagePaths = $files | ForEach-Object { "'/assets/$($p.folder)/$_'" }
            $images = "[" + ($imagePaths -join ", ") + "]"
        }
    } elseif ($p.images) {
        $imagePaths = $p.images | ForEach-Object { "'$_'" }
        $images = "[" + ($imagePaths -join ", ") + "]"
    }

    $jsContent += @"

  {
    id: $($p.id),
    slug: "$($p.slug)",
    title: "$($p.title)",
    categorySlug: "$($p.category)",
    toolsUsed: "$($p.tools)",
    description: "$($p.desc)",
    fullDescription: "$($p.full)",
    videoUrl: "$($p.video)",
    images: $images,
  },
"@
}

$jsContent += "];`n"

Set-Content -Path "src/data/projects.js" -Value $jsContent
